/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */

import io.kotest.core.spec.style.DescribeSpec
import io.kotest.matchers.shouldBe


class GameTests : DescribeSpec({
    describe("game") {

        var game = Game()

        beforeEach {
            game = Game()
        }

        it("score returns zero") {
            game.score() shouldBe 0
        }
    }
})
