/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */

import io.kotest.core.spec.style.DescribeSpec
import io.kotest.matchers.shouldBe


class MainTests : DescribeSpec({
    describe("library") {
        it("someLibraryMethod returns true") {
            val classUnderTest = Library()
            classUnderTest.someLibraryMethod() shouldBe true
        }
    }
})
