/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */

import io.kotest.core.spec.style.DescribeSpec
import io.kotest.matchers.shouldBe


class GameTests : DescribeSpec({
    describe("game") {
        it("someLibraryMethod returns true") {
            val classUnderTest = Game()
            classUnderTest.someLibraryMethod() shouldBe true
        }
    }
})
